/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    "You wake up in a bare room.": "你在一个空荡荡的房间里醒来。",
    "Teleport From Rune": "从符文传送",
    "Sync Clones": "同步克隆",
    "Stuff": "物品",
    "Stats": "属性",
    "Spells": "法术",
    "Some people.": "一些人。",
    "Teleport To Rune": "传送到符文",
    "The game automatically saves every time a reset occurs.": "每次重置时游戏都会自动保存。",
    "The game warns on clearing queues.": "游戏会对清除队列发出警告。",
    "This will put your current queues on your clipboard.": "这将把当前队列放在剪贴板上。",
    "This will put your save on your clipboard.": "这将保存您的存档到剪贴板。",
    "times": "次",
    "Time (B)": "时间 (B)",
    "Travel back in time (R": "时光倒流 (R",
    "Use WASD": "使用 WASD",
    "Using": "使用",
    "View messages": "查看消息",
    "Wait when any complete": "等待任何完成",
    "Weaken Rune": "削弱符文",
    "Welcome to Cavernous!": "欢迎来到循环洞穴！",
    "Wither Rune": "凋零符文",
    "Runes": "符文",
    "Routes (click to load": "路线 (单击加载",
    "Route values wil be reset on the next visit.": "路线值将在下次访问时重置。",
    "Return to your little room.": "回到你的小房间。",
    "Restart to improve your skills when the queue is empty.": "当队列为空时重新开始以提高您的技能。",
    "Repeatedly Interact": "反复互动",
    "Repeat following action(s": "重复以下动作",
    "Repeat all actions after this action.": "在此操作后重复所有操作。",
    "Reminisce about the 'story'.": "回忆“故事”。",
    "Pause the game to more easily adjust your queue.": "暂停游戏以更轻松地调整您的队列。",
    "Actions": "动作",
    "Clear": "清除",
    "Arcane Shield Spell": "奥术护盾法术",
    "All": "全部",
    "Adjust what happens when clicking on a zone route.": "调整当点击区域路线时发生的事情。",
    "Delete": "删除",
    "Config": "配置",
    "Click anywhere to continue.": "点击任意位置继续。",
    "Clear Save (double click": "清除保存(双击)",
    "cannot be consumed": "不能使用",
    "can be consumed about": "可以消耗大约",
    "arrow keys": "方向键",
    "but you have a feeling you'll be back here again.": "但你觉得你还会回来的。",
    "Are you sure you want to restart the game?": "您确定要重新启动游戏吗?",
    "If other clones have sync actions, wait until they're all on sync actions.": "如果其他克隆具有同步操作，则等待它们都处于同步操作。",
    "If you're offline or your computer runs slowly, time is banked (at 50% efficiency) - you can use it to speed up the game!": "如果你离线或你的电脑运行缓慢，时间被储存(以50%的效率)-你可以用它来加速游戏!",
    "Import Queue": "导入队列",
    "Interact": "交互",
    "Load only zone route": "仅加载区域路线",
    "Manually Save": "手动保存",
    "Map (": "地图 (",
    "Move around with": "四处走动 使用",
    "Move down": "向下",
    "Move left": "向左",
    "Move right": "向右",
    "Move up": "向上",
    "Mystic Blade Spell": "神秘之刃法术",
    "Not grinding mana rocks": "不刷魔法石",
    "One of the walls looks soft enough for you to dig through,": "有一堵墙看起来很软，你可以挖过去，",
    "Options": "选项",
    "Paste queues in the box.": "在框中粘贴队列。",
    "Paste your save in the box.": "将存档粘贴到方框中。",
    "Pathfind Here (F": "在这里寻路 (F",
    "Tab selects the next clone": "Tab键选择下一个克隆",
    "Support Development": "支持开发",
    "Space to act at your location": "在您的位置采取行动的空间",
    "Showing Warnings": "显示警告",
    "Selected Location": "选定地点",
    "Select all": "全选",
    "Running": "运行",
    "Loops through your best paths to each mana rock.": "循环通过你的最佳路径到达每个法力石。",
    "Import": "导入",
    "Export Queue": "导出队列",
    "Export": "导出",
    "Erase": "擦除",
    "Duplication Rune": "复制符文",
    "Double click to revisit all known mana rocks.": "双击以重新访问所有已知的法力石。",
    "Ctrl-click selects multiple clones": "按住 Ctrl+单击 选择多个克隆",
    "Ctrl-backspace clears the whole queue": "按 Ctrl+退格键 清除整个队列",
    "Ctrl-A selects all clones": "Ctrl-A 选择所有克隆",
    "Backspace removes a command": "退格键删除一个命令",
    "Arrow keys to move": "方向键移动",
    "1-3 to inscribe a rune": "1-3 铭刻符文",
    "Time spent": "花费时间",
    "Version": "版本",
    "Clones lost": "克隆丢失",
    "Est. mana left": "估计法力剩余",
    "Load best route to this rock": "加载到这块岩石的最佳路线",
    "Mana used": "使用的法力",
    "Mouse over to see key bindings.": "将鼠标悬停以查看键绑定。",
    "Probably ": "大概",
    "right now": "马上",
    "Route time": "路线时间",
    "Stuff used": "使用的物品",
    "There is no known routes to this location.\n": "没有到此位置的已知路线。\n",
    "There is no known valid route to this location - check your prerequisites!\n": "没有到此位置的已知有效路径 - 请检查您的先决条件！\n",
    "Bridge": "桥",
    "Shield": "盾",
    "Sword": "剑",
    "This is probably pretty valuable.  Shiny!": "这可能是非常有价值的。 精彩！",
    "This time, you feel slightly more competent than last time.": "这一次，你感觉比上一次稍微胜任了。",
    "Time Travel": "时间旅行",
    "to clear queue": "清除队列",
    "to extract mana from those rocks.": "从那些岩石中提取法力。",
    "to interact": "互动",
    "to move": "移动",
    "to remove last action": "删除最后一个动作",
    "Wait when all complete": "等待全部完成",
    "You're back in the room you first found yourself in.": "你回到了你第一次发现自己所在的房间。",
    "Hammer": "锤",
    "Axe": "斧",
    "Pick": "镐",
    "Ore": "矿石",
    "Bar": "条",
    "Armour": "甲",
    "Spacebar": "空格键",
    "spacebar": "空格键",
    "Salt": "盐",
    "Restart when complete": "完成后重启",
    "Restart always": "总是重启",
    "Paused": "已暂停",
    "Mana": "法力",
    "Load prereqs": "加载先决条件",
    "Is that because you now know a little of the cave you're in?": "那是因为你现在对你所在的洞穴有一点了解吗？",
    "If you haven't found a mana rock, maybe keep looking!": "如果你还没有找到法力岩石，也许继续寻找！",
    "How long you can resist being pulled back to your cave.": "你能抵抗多久被拉回你的洞穴。",
    "Grinding mana rocks": "研磨法力石",
    "Gold Nugget": "金块",
    "Given time, you're sure you can find a way out.": "给定时间，你肯定能找到出路。",
    "Ctrl+Backspace": "Ctrl+退格键",
    "Controls": "控制",
    "Coal": "煤",
    "Banking": "银行",
    "Backspace": "退格键",
    "Arrows": "箭头",
    "And while you haven't, it would be good to use the": "虽然你还没有，但最好使用",
    "An suit of iron armour.  This should help you take more hits. (+5 health)  Max 1 armour per clone.": "一套铁甲。 这应该可以帮助您获得更多点击次数。 （+5 生命值）每个克隆最多 1 件盔甲。",
    "An iron sword.  Sharp! (+1 attack)  Max 1 weapon per clone.": "一把铁剑。 锋利的！ （+1 攻击）每个克隆最多 1 件武器。",
    "An iron shield.  This should help you not die. (+1 defense)  Max 1 shield per clone.": "一个铁盾。 这应该可以帮助你不死。 （+1 防御）每个克隆最多 1 个盾牌。",
    "An iron rod.  Has a faint smell of bacon.": "一根铁棒。 有淡淡的熏肉味。",
    "An iron pickaxe.  Gives +15 (or +15%) to Mining, and applies 1% of your Mining skill to combat.": "一把铁镐。 为采矿提供 +15（或 +15%），并将 1% 的采矿技能应用于战斗。",
    "An iron hammer.  Gives +15 (or +15%) to smithing, and applies 1% of your Smithing skill to combat.": "铁锤。 为锻造提供 +15（或 +15%），并将 1% 的锻造技能应用于战斗。",
    "An iron axe.  Gives +15 (or +15%) to Woodcutting, and applies 1% of your Woodcutting skill to combat.": "一把铁斧。 为伐木提供 +15（或 +15%），并将 1% 的伐木技能应用于战斗。",
    "A suit of steel armour.  This should help you take more hits. (+15 health)  Max 1 armour per clone.": "一套钢盔甲。 这应该可以帮助您获得更多点击次数。 （+15 生命值）每个克隆最多 1 件盔甲。",
    "A steel sword.  Sharp! (+2 attack)  Max 1 weapon per clone.": "一把钢剑。 锋利的！ （+2 攻击）每个克隆最多 1 件武器。",
    "A steel shield.  This should help you not die. (+2 defense)  Max 1 shield per clone.": "一个钢盾。 这应该可以帮助你不死。 （+2 防御）每个克隆最多 1 个盾牌。",
    "A steel rod.": "一根钢棒。",
    "A small steel bridge.": "一座小钢桥。",
    "A small iron bridge.": "一座小铁桥。",
    "A pile of salt.  You're not hungry, so what's this good for?": "一堆盐。 你不饿，这有什么用？",
    "A chunk of coal.  Burns hot.": "一大块煤。 灼热。",
    "A chunck of iron ore.  Not useful in its current form.": "一大块铁矿石。 在当前形式下没有用。",
    "A whole bunch of relatively soft rock.": "一大堆相对较软的岩石。",
    "Limestone": "石灰石",
    "Mining": "采矿",
    "Speed": "速度",
    "A bare stone passage, empty of any ornamentation.": "一条光秃秃的石头通道，没有任何装饰。",
    "A giant mushroom which grows quickly.  It's harder to cut the longer you wait.": "一种生长迅速的巨型蘑菇。 等待的时间越长，切割就越困难。",
    "A whole bunch of rock.  But this time, it glows!": "一大堆石头。 但这一次，它发光了！",
    "Mana-infused Rock": "注入魔力的岩石",
    "Messages": "消息",
    "ore": "矿石",
    "Mushroom": "蘑菇",
    "Out of Mana": "法力耗尽",
    "Rocks with veins of iron ore.": "有铁矿脉的岩石。",
    "Solid Rock": "坚硬的岩石",
    "Tunnel": "隧道",
    "Some kind of rock, too hard to dig through.": "某种岩石，太难挖了。",
    "Use arrow keys": "使用箭头键",
    "Rocks with veins of gold ore.": "带有金矿脉的岩石。",
    "Gold ore": "金矿石",
    "Woodcutting": "伐木",
    "Vaporizer": "喷雾器",
    "Smithing": "锻造",
    "Runic Lore": "符文知识",
    "Magic": "魔法",
    "Kudzushroom": "葛菇",
    "How many hits you can take until you're nothing more than meat. (Armour increases all clones' stats": "你能承受多少打击，直到你变成肉块。(盔甲增加所有克隆的属性",
    "Health": "生命值",
    "Complete Goal": "完成目标",
    "Combat": "战斗",
    "An anvil on which you can make an axe out of an iron bar.": "一个铁砧，你可以在上面用铁棒制作斧头。",
    "An anvil on which you can make a pick out of an iron bar.": "一个铁砧，你可以在上面用铁棒制作镐子。",
    "A wall of rock salt.  It only takes so long to mine it because you want to sort out the salt and not carry a ton of gravel with you.": "岩盐墙。 开采它只需要很长时间，因为你想把盐分出来，而不是随身携带一吨砾石。",
    "A strange energy field where you can obtain additional powers.": "一个奇怪的能量场，你可以获得额外的力量。",
    "A machine for extracting the magic right out of gold.": "从黄金中提取魔法的机器。",
    "A giant mushroom which grows quickly.  It grows so fast each clone needs to make its own way every time.": "一种生长迅速的巨型蘑菇。 它增长得如此之快，每个克隆每次都需要走自己的路。",
    "Not showing warnings": "不显示警告",
    "Showing warnings": "显示警告",
    "Multiple clones use up the same amount of mana as a single clone, and they can act independently or help each other out by cooperating on the same task.": "多个克隆与单个克隆消耗相同数量的法力，他们可以独立行动或通过合作完成同一任务来互相帮助。",
    "panel for the": "面板",
    "Second Clone": "第二克隆",
    "Setting it to \"Wait when any complete\" will ignore clones that end with a Sync (=) action.": "将它设置为\“当任何完整的\”将忽略以同步(=)动作结束的克隆。",
    "Strip Mining": "露天开采",
    "sync": "同步",
    "That goblin killed one of your clones!": "那个地精杀死了你的一个克隆！",
    "The Looping of Looping Loops": "循环循环的循环",
    "The time repeats itself over and over, the cave stays the same.": "时间一遍又一遍地重演，洞穴保持不变。",
    "There are many mana rocks, but the shortest path is always the best one.": "魔石有很多，但最短的路径永远是最好的。",
    "to automatically select the fastest path": "自动选择最快路径",
    "Two clones can work in the same space, taking half the time it takes one clone to complete the job.": "两个克隆可以在同一个空间工作，完成工作所需的时间是一个克隆的一半。",
    "Unlike normal interact, if you don't have the resources to start an interact action, it'll just skip it entirely.": "与普通交互不同，如果您没有资源来启动交互操作，它会完全跳过它。",
    "Use CTRL-click to select more than one clone or CTRL-A to select them all.  Tab rotates through them.": "使用 CTRL-单击选择多个克隆或使用 CTRL-A 选择所有克隆。 选项卡在它们之间旋转。",
    "What you thought was a strange statue in the passage suddenly moves to attack you as you approach!  This place is stranger than you'd thought.": "你以为是通道里的一尊奇怪的雕像，在你靠近的时候突然动了起来攻击你！ 这个地方比你想象的要陌生。",
    "You can create more clones by bringing more gold to a Clone Machine.  Click on a Clone Machine to find out how much the next clone costs.": "您可以通过为克隆机器带来更多金币来创建更多克隆。 单击克隆机器以了解下一个克隆的成本。",
    "You can probably mine those rocks a few additional times with that.": "你可能可以用它再开采几次这些岩石。",
    "You can view a zone by clicking on it, and hovering it shows a summary of the routes you've beaten it with.  You can click on these routes to load them.  There's an option which lets you load only that route or that route and its prerequisites.": "您可以通过单击一个区域来查看它，并将其悬停会显示您击败它的路线的摘要。 您可以单击这些路由来加载它们。 有一个选项可让您仅加载该路线或该路线及其先决条件。",
    "You might not need it now, but later in the game it can really help with making sure your clones line up when forging bars or vaporizing gold.": "您现在可能不需要它，但在游戏后期，它确实可以帮助确保您的克隆体在锻造金条或蒸发黄金时排列整齐。",
    "You'll have to go out and find another rock to extract mana from.": "你必须出去寻找另一块岩石来提取法力。",
    "You'll need to achieve a high enough current value for your base to increase.": "您需要达到足够高的电流值才能增加基数。",
    "You've created another clone!  Remember, these clones can work together.": "您已经创建了另一个克隆！ 请记住，这些克隆可以协同工作。",
    "You've created your first clone!  It can carry out actions in exactly the same way you can.": "你已经创建了你的第一个克隆！ 它可以以与您完全相同的方式执行操作。",
    "You've found a portal to another zone!": "你找到了通往另一个区域的传送门！",
    "You've run out of mana.  You feel drawn back to the room where you started.": "你的法力用完了。 你感觉回到了你开始的房间。",
    "You've sure got a lot of iron!  You can use the Repeat-Interact action to forge it all into bars.  Use ctrl-space to insert a Repeat-Interact action into your queue.": "你肯定有很多铁！ 您可以使用重复交互操作将其全部锻造成条形。 使用 ctrl+空格键 将重复交互操作插入到您的队列中。",
    "your clones and have them attack together, you might have better luck.  Or maybe you need to craft more or better weapons.": "你的克隆并让他们一起攻击，你可能会有更好的运气。 或者您可能需要制作更多或更好的武器。",
    "(Click \"Travel back in time\" or press the": "（点击“时光倒流”或按",
    "), and your current value is reset to your base value when you travel back in time.": ")，当您回到过去时，您的当前值将重置为您的基本值。",
    "All the known ways": "所有已知的方式",
    "Auto-Grind": "自动研磨",
    "base": "基础",
    "Auto-Restart requirement (W": "自动重启要求（W",
    "Buy More Time": "购买更多时间",
    "Check the": "查看",
    "Check the right panel to estimate how many more times you can consume this rock": "检查右侧面板以估计您可以消耗这块岩石的次数",
    "current": "当前",
    "Death": "死亡",
    "Despite going back in time, your skills are slowly improving.  You can perform actions faster than before!": "尽管时光倒流，但您的技能正在慢慢提高。 您可以比以前更快地执行操作！",
    "Each stat is displayed as": "每个统计信息显示为",
    "Each zone has at least 3 mana rocks - they give more mana but their cost scales faster the deeper you get.  They give 0.1 mana to each zone up to the current one, which you'll receive on entering that zone.": "每个区域至少有 3 块法力石——它们提供更多法力，但越深，它们的成本增加得越快。 它们为每个区域提供 0.1 法力，直到当前区域，您将在进入该区域时收到。",
    "Enter New Zone": "进入新区域",
    "First Clone": "第一个克隆",
    "Fortunately for you, death is not the end.  Surely you'll be able to overcome this obstacle in short order.": "对你来说幸运的是，死亡并不是结束。 当然，您将能够在短时间内克服这个障碍。",
    "Goblin": "哥布林",
    "Have you found the Vaporizer yet?  Interacting with it will turn your gold into mana!": "你找到蒸发器了吗？ 与它互动会将你的黄金变成法力！",
    "Hovering over a stat displays the percentage of time you save on tasks using that stat.": "将鼠标悬停在统计数据上会显示您使用该统计数据在任务上节省的时间百分比。",
    "It's getting harder to extract mana from that rock.": "从那块岩石中提取法力变得越来越困难。",
    "If you": "如果你",
    "It's probably a good thing that you can get along with yourself - it would get messy quick if you couldn't.": "你能和自己相处可能是件好事——如果你不能，它会很快变得混乱。",
    "key": "钥匙",
    "Learning": "学习",
    "Mass Manufacturing": "大规模制造",
    "Maybe you can come back to this one later when you have more mana to spend on it.": "也许当你有更多的法力可以花在这上面时，你可以再回来玩这个。",
    "A bottomless pit.": "一个无底洞。",
    "An anvil on which you can make a hammer out of an iron bar.": "一个铁砧，你可以在上面用铁棒制作锤子。",
    "Granite": "花岗岩",
    "Mana Spring": "法力之泉",
    "Pure mana, flowing out of the rock.  Each time you absorb the mana, the cost to do so next time increases.": "纯净的法力，从岩石中流出。 每次吸收法力，下次这样做的成本都会增加。",
    "Pit": "坑洞",
    "This stone just doesn't want to budge.": "这块石头就是不想让步。",
    "Portal": "传送门",
    "A portal to another zone.": "通往另一个区域的门户。",
    "Bottomless Pit": "无底洞",
    "Dug Tunnel": "挖隧道",
    "Furnace": "熔炉",
    "Gold Ore": "金矿石",
    "Goal": "目标",
    "Strange Machine": "奇怪的机器",
    "Zone Portal": "区域门户",
    "You can find the cost to place a rune in that rune's tooltip.": "您可以在该符文的工具提示中找到放置符文的成本。",
    "You worked so hard on that bridge, and to see it quickly turn to slag after crossing that lava is sad.": "你在那座桥上辛苦了，在穿过那座熔岩后看到它很快变成了渣，很伤心。",
    "You've unlocked a rune!": "你解锁了一个符文！",
    "A large box full of fire.": "一个装满火的大箱子。",
    "An anvil on which you can make a bridge out of 2 iron bars.": "一个铁砧，您可以在其上用 2 根铁条搭桥。",
    "At least one of your clones made it across.": "至少你的一个克隆通过了。",
    "Lava Can't Melt Steel Bridges": "熔岩不能融化钢桥",
    "Requires": "要求",
    "The Weaken rune reduces the attack and defense of adjacent enemies by 1 point each (but not below 0).": "虚弱符文使相邻敌人的攻击和防御各降低 1 点（但不低于 0）。",
    "The Wither rune kills plants next to it.  After placing it, interact with it to charge it up and kill adjacent plants.": "凋零符文会杀死旁边的植物。 放置后，与它互动以为其充电并杀死相邻的植物。",
    "This rune allows you to kill even hardy plants.  Interact with it to charge it up.": "这个符文可以让你杀死甚至耐寒的植物。 与它互动以充电。",
    "This rune weakens any orthogonally adjacent enemies, decreasing their attack and defense by 1.": "该符文削弱任何正交相邻的敌人，使其攻击和防御降低 1。",
    "To place a rune, press the relevant number, and the rune will be inscribed upon the space that clone is in.  You can inscribe runes only on Dug Tunnel spaces.": "要放置符文，请按相关数字，符文将刻在克隆所在的空间上。您只能在挖隧道的空间中刻上符文。",
    "Unlocked Weaken Rune": "解锁弱化符文",
    "Unlocked Wither Rune": "解锁凋零符文",
    "Weaken": "虚弱",
    "Wither": "凋零",
    "Check zone route usage": "检查区域路线使用情况",
    "Core": "核心",
    "Expected completions": "预计完工",
    "For performance reasons, the blue shading on unused zone routes may not update frequently; this forces an update.": "出于性能原因，未使用区域路由上的蓝色阴影可能不会经常更新； 这会强制更新。",
    "Forget this route": "忘记这条路线",
    "If you're offline or your computer runs slowly, time is banked (at 100% efficiency) - you can use it to speed up the game!": "如果您处于离线状态或计算机运行缓慢，则可以节省时间（效率为 100%） - 您可以使用它来加快游戏速度！",
    "This route ends with all your clones dead!\n": "这条路线以你所有的克隆人死亡告终！\n",
    "This rune allows you to kill even hardy plants.  Interact with it to charge it up - it takes as much time to charge as the plants you're trying to kill would take to chop.": "这个符文可以让你杀死甚至耐寒的植物。 与它互动以为其充电 - 充电所需的时间与您试图杀死的植物所需的时间一样长。",
    "Hide timeline": "隐藏时间线",
    "Show timeline": "显示时间线",
    "Stay on selected zone": "留在选定的区域",
    "There are a bunch more options.": "还有更多的选择。",
    "Total": "总计",
    "View more config": "查看更多配置",
    "You can also double-click on the Grind option.": "您也可以双击研磨选项。",
    "A gem, pulled from the ground.  Gives +2.5 (or +2.5%) to Magic.": "一颗宝石，从地上挖出来。 为魔法提供 +2.5（或 +2.5%）。",
    "A giant mushroom which grows quickly.  It grows so fast each clone needs to make its own way every time. (Growth: 1+0.1t": "一种生长迅速的巨型蘑菇。 它增长得如此之快，每个克隆每次都需要走自己的路。 （增长：1+0.1t",
    "Adjust what happens when your clones the zone you're currently viewing.": "调整克隆当前正在查看的区域时发生的情况。",
    "An iron hammer.  Gives +15 (or +15%) to Smithing, and applies 1% of your Smithing skill to combat.": "铁锤。 为锻造提供 +15（或 +15%），并将 1% 的锻造技能应用于战斗。",
    "can be refined about": "可以细化大约",
    "Follow on zone complete": "跟随区域完成",
    "cannot be refined": "无法提炼",
    "It's a neat feature, but it might be a little eye-grabbing.": "这是一个简洁的功能，但它可能有点引人注目。",
    "Revisit all known mana rocks in this realm": "重温这个领域所有已知的法力岩石",
    "Route values will be reset on the next visit.": "路线值将在下次访问时重置。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Discord': 'Discord',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t\t\t\t": "\t\t\t\t\t\t",
    "\t\t\t\t\t": "\t\t\t\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "Iron ": "铁",
    "Steel ": "钢",
    "How quick you are. (": "你有多快。 (",
    "Increase at: ": "增加在：",
    "Time: ": "时间: ",
    "Your skill at mining, reducing the time it takes to do mining-type tasks. (": "您的采矿技能，减少了执行采矿类任务所需的时间。 (",
    "Next: ": "下一个: ",
    "Anvil - ": "铁砧 - ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t\t\t": "\n\t\t\t\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\t\t\t\t\t": "\t\t\t\t\t",
    "\n\t\t": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+) \(([\d\.]+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)\:([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Your understanding of arcane mysteries. \((.+)$/, '你对神秘奥秘的理解。 \($1'],
    [/^How good you are at chopping down mushrooms of various kinds. \((.+)$/, '你是多么擅长切各种蘑菇。 \($1'],
    [/^A measure of your understanding of magical runes. \((.+)$/, '衡量你对魔法符文的理解。\($1'],
    [/^Your ability to kill things. \((.+)$/, '你杀死事物的能力。 \($1'],
    [/^Your skill at turning raw ores into usable objects. \((.+)$/, '您将原始矿石变成可用物品的技能。 \($1'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^A giant mushroom which grows quickly.  It's harder to cut the longer you wait. \(Growth: (.+)$/, '一种生长迅速的巨型蘑菇。 等待的时间越长，切割就越困难。 （生长：$1'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Mana-infused Rock (.+)s$/, '法力注入岩 $1秒'],
    [/^Mana Spring (.+)s$/, '法力泉 $1秒'],
	[/^Zone ([\d\.]+)$/, '区域 $1'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+) Iron Bar$/, '$1 铁锭'],
	[/^([\d\.]+) Gold Nugget$/, '$1 金块'],
	[/^([\d\.]+) Iron Ore$/, '$1 铁矿石'],
	[/^([\d\.]+) Salt$/, '$1 盐'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);